name: Staging Deployment

on:
  pull_request:
    types: ['opened', 'synchronize', 'reopened']
    branches:
      - 'hotfix/*'
      - 'release/*'
  push:
    tags:
      - v*.*.*

env:
  NODE_VERSION: '18.16.0'
  ENV: 'staging'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
