name: PR Validation

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited, locked]

env:
  NODE_VERSION: '18.16.0'
jobs:
  validate-title:
    runs-on: ubuntu-latest
    name: PR Title Check
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies and configure
        run: |
          npm init -y
          npm install -D @commitlint/cli @commitlint/config-angular @commitlint/config-angular-type-enum commitlint-plugin-function-rules
          echo "const types = require('@commitlint/config-angular-type-enum'); module.exports = {extends: ['@commitlint/config-angular'], plugins: ['commitlint-plugin-function-rules'], rules: {'scope-case': [0],'function-rules/scope-case': [2, 'always', parsed => !parsed.scope || /^MV-\d+$/.test(parsed.scope) ? [true] : [false, 'scope has to be the format MV-X where X is a number']], 'type-enum': [2, 'always', [...types.value(), 'release', 'chore']]}}" > commitlint.config.js

      - name: Lint PR title
        run: |
          PR_TITLE=$(gh pr view https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }} --json title -q ".title")
          echo $PR_TITLE | npx commitlint
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
