name: Slack Notification for Release

on:
  release:
    types:
      - published

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Release Note
        id: prepare
        run: |
          RELEASE_NOTE=$(echo "${{ github.event.release.body }}" | jq -R --slurp | jq -c .)
          echo "RELEASE_NOTE_JSON=$RELEASE_NOTE" >> $GITHUB_ENV
          echo $RELEASE_NOTE

      - name: Send Release Notification to Slack using curl
        run: |
          PAYLOAD=$(cat <<- EOM
            {
              "text": "New release is out: ${{ github.event.release.name }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*${{ github.event.release.name }}* - Release Notes\n${{ env.RELEASE_NOTE_JSON }}\n\n<${{ github.event.release.html_url }}|View Release on GitHub>"
                  }
                }
              ]
            }
          EOM
          )
          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" ${{ secrets.SLACK_WEBHOOK_URL }}
