name: Slack Notification for Release

on:
  release:
    types:
      - published

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release Notification to Slack
        run: |
          RELEASE_BODY_ESCAPED=${{ github.event.release.body }}
          RELEASE_BODY_ESCAPED="${RELEASE_BODY_ESCAPED//\"/\\\"}" # Escape double quotes
          PAYLOAD=$(cat <<- EOM
            {
              "text": "New release is out: ${{ github.event.release.name }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*${{ github.event.release.name }}* - Release Notes\n$RELEASE_BODY_ESCAPED\n\n<${{ github.event.release.html_url }}|View Release on GitHub>"
                  }
                }
              ]
            }
          EOM
          )
          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" ${{ secrets.SLACK_WEBHOOK_URL }} --fail
