name: Slack Notification for Release

on:
  release:
    types:
      - published

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Release Note
        id: prepare
        run: |
          RELEASE_NOTE=$(echo '${{ github.event.release.body }}' | python3 -c "import sys, json; print(json.dumps(sys.stdin.read()))")
          echo "RELEASE_NOTE_JSON=$RELEASE_NOTE" >> $GITHUB_ENV

      - name: Send Release Notification to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "New release is out: ${{ github.event.release.name }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*${{ github.event.release.name }}* - Release Notes\n${{ env.RELEASE_NOTE_JSON }}\n\n<${{ github.event.release.html_url }}|View Release on GitHub>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
