name: Slack Notification for Release

on:
  release:
    types:
      - published

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Release Note
        id: prepare
        run: |
          RELEASE_NOTE="${{ github.event.release.body }}"
          echo "RELEASE_NOTE=${RELEASE_NOTE//[$'\t\r\n']}___NEWLINE___" >> $GITHUB_ENV

      - name: Send Release Notification to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "New release is out: ${{ github.event.release.name }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*${{ github.event.release.name }}* - Release Notes\n${{ env.RELEASE_NOTE }}\n\n<${{ github.event.release.html_url }}|View Release on GitHub>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
